name: Generate SBOM

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Go (you can specify the version you need)
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      # Step 3: Install CycloneDX GoMod
      - name: Install CycloneDX GoMod
        run: |
          go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@latest

      # Step 4: Generate the SBOM
      - name: Generate SBOM
        run: |
          cyclonedx-gomod app -o bom.xml

      # Step 5: Upload the SBOM as an artifact (optional)
      - name: Upload SBOM
        uses: actions/upload-artifact@v2
        with:
          name: bom.xml
          path: bom.xml
